#!/bin/bash

# postrm
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

case "$1" in
    remove|upgrade)
        # Remove startvnc
        sed -i '/startvnc/d' /etc/xdg/lxsession/LXDE/autostart
        ;;
esac

#DEBHELPER#

exit 0
