#!/bin/sh

# vncglobals
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
# Global variables to be shared across VNC related scripts
#

VNC_PATH=~/.vnc
PASS_FILE=$VNC_PATH/passwd
VNC_DISPLAY=":0"
SHINCOMING="/usr/share/kano-vnc/vncincoming"
VNCAPP="/usr/bin/x11vnc"

VNC_CMDLINE="$VNCAPP -rfbauth $PASS_FILE -display $VNC_DISPLAY -no6 -noipv6 -dontdisconnect -forever -shared -nolookup -ungrabboth -accept \"$SHINCOMING\" -N -bg"
